"""add unique constraint to intersection name

Revision ID: 69a59122d663
Revises: cbdcc06d53d7
Create Date: 2026-07-13 23:40:01.147114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69a59122d663'
down_revision: Union[str, Sequence[str], None] = 'cbdcc06d53d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'intersections', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'intersections', type_='unique')
    # ### end Alembic commands ###
