"""add constraints to intersections

Revision ID: 8d32a0cd70ce
Revises: 69a59122d663
Create Date: 2026-07-14 16:30:57.658666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d32a0cd70ce'
down_revision: Union[str, Sequence[str], None] = '69a59122d663'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('intersections_name_key'), 'intersections', type_='unique')
    op.create_index(op.f('ix_intersections_city'), 'intersections', ['city'], unique=False)
    op.create_index(op.f('ix_intersections_name'), 'intersections', ['name'], unique=True)
    op.create_index(op.f('ix_intersections_status'), 'intersections', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_intersections_status'), table_name='intersections')
    op.drop_index(op.f('ix_intersections_name'), table_name='intersections')
    op.drop_index(op.f('ix_intersections_city'), table_name='intersections')
    op.create_unique_constraint(op.f('intersections_name_key'), 'intersections', ['name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
