from enum import StrEnum


class EventType(StrEnum):
    """
    Standardized application events.
    """

    APP_STARTED = "APP_STARTED"
    APP_STOPPED = "APP_STOPPED"

    HEALTH_CHECK = "HEALTH_CHECK"

    SIGNAL_CHANGED = "SIGNAL_CHANGED"

    EDGE_AI_FAILED = "EDGE_AI_FAILED"
    SERVER_AI_FAILED = "SERVER_AI_FAILED"

    TIME_BASED_FALLBACK = "TIME_BASED_FALLBACK"

    MANUAL_OVERRIDE = "MANUAL_OVERRIDE"

    CAMERA_OFFLINE = "CAMERA_OFFLINE"

    DATABASE_CONNECTED = "DATABASE_CONNECTED"
    DATABASE_DISCONNECTED = "DATABASE_DISCONNECTED"

    REQUEST_STARTED = "REQUEST_STARTED"
    REQUEST_COMPLETED = "REQUEST_COMPLETED"
    REQUEST_FAILED = "REQUEST_FAILED"

    INTERSECTION_CREATED = "INTERSECTION_CREATED"

    APPLICATION_ERROR = "APPLICATION_ERROR"
    VALIDATION_ERROR = "VALIDATION_ERROR"